project:
  type: website
  output-dir: _site

website:
  page-navigation: true # não funciona
  back-to-top-navigation: true
  image: unifal-logo.png # não funciona
  reader-mode: true # funciona
  google-analytics: "G-S1L73VGCG5"
  title: "ERRE - Ensino Reprodutível" # omite-se o título pra não duplicar nome na aba
  favicon: avatar.png # ícone da aba da página
  page-footer: 
        left: |
          Curso de Formação em Educação Digital
        center: |
            UNIFAL-MG
        right: |
           Página criada com pacote Quarto
  
  sidebar:
  # collapse: true # não funcionou- menu lateral minimizado
    contents:
      - section: "Ensino Reprodutível & Objetos Didáticos"
        contents:
          - text: "ERRE"
            href: index.qmd
          - text: "Saudações"
            href: saudacoes.qmd
          - text: "Algumas questões"
            href: questoes.qmd
          - text: "Caixa de Ferramentas"
            href: ferramentas.qmd
      - section: "Moléculas em 3D com Jmol"
        contents:
          - text: "1 - Jmol"
            href: jmol.qmd
          - text: "2 - Mouse *versus* Comandos"
            href: textoXmouse.qmd
          - text: "3 - Alguns comandos do Jmol"
            href: comandosJmol.qmd
          - text: "4 - Algumas animações com Jmol"
            href: anima_Jmol.qmd
          
      - section: "Gráficos Interativos com R"
        contents:
          - text: "1 - R & RStudio"
            href: rstudioCloud.qmd
          - text: "2 - Um pouco sobre uso do `R`"
            href: basicaoR.qmd
          - text: "3 - Pacotes do R"
            href: pacotes.qmd
          - text: "4 - O pacote `plotly`"
            href: plotly.qmd
          - text: "5 - Gráficos interativos com `plotly`"
            href: plotly_interat.qmd
          - text: "6 - Embelezando o gráfico"
            href: plotly_embeleza.qmd
          - text: "7 - Mais interatividade aos gráficos"
            href: plotly_maisInterat.qmd
          - text: "8- Animação em gráficos interativos"
            href: plotly_anima.qmd
          - text: "9 - Mapas interativos (`plotly` e `leaflet`)"
            href: plotly_maps.qmd
          
      - contato.qmd
      
            
            
  navbar:
    search: true
    logo: logo-unifal.png # logo ao lado esquerdo da Home
    background: primary # cor de fundo
    tools:  # ícones específico
      # - icon: twitter
      #   href: https://twitter.com
      - icon: bank
        menu:
          - text: UNIFAL-MG
            href:  https://www.unifal-mg.edu.br/portal/index/
          - text: Depto. Bioquímica
            href:  https://www.unifal-mg.edu.br/dbq/
            
      
  
    left:
      - text: "Curso de Capacitação Ao Ensino Médio"
        menu:
          - text: "Introdução"
            href: Portfolio/JmolBook/iniciativa_Jmol.qmd
            
            
      - text: "Jardim de Moléculas"
        menu:
          - text: "Introdução"
            href: Portfolio/JmolBook/iniciativa_Jmol.qmd
          - text: "Classificação"
            href: Portfolio/JmolBook/classifica.qmd
          - text: "Orgânicas"
            href: Portfolio/JmolBook/organica.qmd
          - text: "Inorgânicas"
            href: Portfolio/JmolBook/inorganica.qmd
          - text: "Biomoléculas"
            href: Portfolio/JmolBook/biomol.qmd
          - text: "Farmacológicas"
            href: Portfolio/JmolBook/farmac.qmd
          - text: "Medicinais"
            href: Portfolio/JmolBook/medicin.qmd
          - text: "Toxicológicas"
            href: Portfolio/JmolBook/toxicol.qmd
          - text: "Nutricionais"
            href: Portfolio/JmolBook/nutri.qmd
          - text: "Supramoleculares"
            href: Portfolio/JmolBook/supramol.qmd
    # right:
    #   - icon: false  # Evitar ícones padrão
    #     href: "https://www.unifal-mg.edu.br/portal/index/"  
    #     html: |
    #      <img src="logo-unifal.png" alt="Universidade Federal de Alfenas" style="height: 30px;"/>  # Ajuste o tamanho da imagem conforme necessário

          
         
            
            # o truque é colocar a pasta dos
            # livros com tudo dentro de alguma
            # pasta do website
      - text: "Gráficos Interativos"
        menu:
          - text: "Introdução"
            href: Portfolio/ODR/iniciativa_ODR.qmd
          - text: "Física"
            href: Portfolio/ODR/ODR.qmd
            target: "_blank"
          - text: "Química"
            href: Portfolio/ODR/ODR.qmd
            target: "_blank"    
          - text: "Biologia"
            href: Portfolio/ODR/ODR.qmd
            target: "_blank"
 
      - text: "Folhas de Dicas"
        menu:
          - text: "Jmol"
            href: Portfolio/Cheatsheet/jmol_cheat.en.pt.pdf
            target: "_blank"
          - text: "Plotly"
            href: Portfolio/Cheatsheet/plotly.pdf
            target: "_blank"    
          - text: "R"
            href: Portfolio/Cheatsheet/r_cheat.en.pt.pdf
            target: "_blank"
           
      - text: "Outros" 
        menu: 
          - text: "Bioquanti"
            href: https://bioquanti.netlify.app/
            target: "_blank"
        
      - contato.qmd
      
      
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
  # include-after-body: collapse-sidebar.js

editor: source
