---
title: "Como baixar o programa Jmol"
---

## Como baixar o programa JMOL?

|       Para baixar o jmol, é necessário acessar o site pelo google: \[Jmol\] (https://sourceforge.net/projects/jmol/), clicar em dowload, será aberta uma pasta no computador com o arquivo em zip, nessa pasta, na opção que corresponde ao jmol, será visível o programa com a utilização do java.Ao abrir essa opção na pasta em zip, com a necessidade do JAVA instalado no computador, é possível que o programa esteja pronto no computador para execução de tarefas relacionadas com moléculas.As exceções exigem comandos relacionados ao jmol, porém as instruções são maleáveis para que o objetivo seja atingido com sucesso.

|       A utilização do Jmol para o ensino, pode ser uma ferramenta beneficiária para alunos e professores, na questão relacionada com ensino e aprendizagem, pois tudo relacionado á tecnologia chama a atenção da nova geração, e é uma maneira de instigar os alunos a aprender através da ferramenta. Visando que os comandos direcionados ao programa exijão um pouco mais de dedicação, o resultado final é satisfatório no sentido de realizar movimentos com as moléculas e alguns efeitos que o programa pode fornecer para uma aprendizagem mais dinâmica e de interação corresponde com a realidade dos alunos, atualmente envolvidos com a internet.Essa realidade ligada com o uso de celulares, internet na sala de aula, no que se diz respeito para aprender, é dar sentido a esses tipos de ações nas salas de aula, mas será permitido o uso de computadores em um espaço obviamente, para que os alunos possam aprender, pois sempre que se deslocam do ambiente formal de estudo e com novas tecnicas de aprendizagem,é uma nova percepção para aprender como as moléculas químicas são formadas e de que maneira elas se comportam no espaço.

|       O resultado final com relação ao ensino e aprendizagem é uma incógnita, mas as intuiçoes são positivas devido ao que relamente desperta o interesse dos alunos, como já foi pontuado, a nova geração é motivada á tecnologia e porque não utiliza-la para o ensino? A perspectiva de utilização do programa no sentido de ensino como também na interação de alunos e professores, no anseio de movimentar todas as questões de dificuldades de ensino para alunos que não se interessam pela didática habitual. Uma vez que as tarefas serão realizads em um ambiente digital que pode promover a aprendizagem mais eficaz e dinâmica.
