---
title: "Gráficos interativos com o pacote `plotly`"
---

## Uma palavrinha sobre alguns pacotes para interatividade gráfica no `R`

|       Entre as duas dezenas de milhar de bibliotecas do `R`, algumas poucas permitem recursos de animação, simulação e interatividade. Elencando algumas brevemente, o pacote [`anim.plots`](https://cran.r-project.org/web/packages/anim.plots/index.html) permite gerar arquivos de animação por imagem (*PNG, GIF*) e mesmo arquivos em formato *PDF*, com as animações pré-definidas pelo usuário, e utilizando-se da biblioteca [`graphics`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2) que já vem na instalação do `R` para a construção de gráficos.
\

|       Por sua vez, o pacote [`manipulate`](https://cran.r-project.org/web/packages/manipulate/index.html) já permite uma interação maior com o usuário, possibilitando a elaboração em tempo real de gráficos de funções matemáticas com alteração em parâmetros. Não obstante, o pacote só opera dentro do ambiente do *RStudio*. Já o pacote `gganimate` utiliza a riqueza da biblioteca (ou pacote) gráfica [`ggplot2`](https://cran.r-project.org/web/packages/ggplot2/index.html) para criar animações em gráficos mais sofisticados, permitindo seu salvamento em formato de imagem (*PNG*), e mesmo em formato *HTML.*
\

|       Já a biblioteca `plotly` é mais rica em interatividade entre as mencionadas acima. Além de produzir gráficos em animação pré-definida pelo usuário, também permite modificar algum parâmetro o variável categórica/numérica, armazena o produto final em arquivo separado (*PNG, HTML*), possibilita facilmente ações de ampliação, redução e foco em determinada região do gráfico, bem como o efeito de *mouse over* (ou *hover*), em que a simples passagem do mouse sobre o dado gráfico abra as informações daquele ponto. E pra fechar o `plotly` é capaz de produzir gráficos de qualidade de publicação ou de grande complexidade integrando-se ao pacote [`ggplot2`](https://cran.r-project.org/web/packages/ggplot2/index.html), além de possibilitar a inserção de seletores, menu suspenso, e de botões.
\

|       Isso é o melhor dos mundos !! Porque, em síntese, é possível criar o gráfico, inserir comandos de animação e interatividade, e armazená-lo em arquivo separado *HTML*, possibilitando-o ser aberto em qualquer *browser*, mesmo estando sem conexão com a internet, em computador ou dispositivo móvel. Isso caracteriza o `ploly` como uma ferramenta potencial ao ensino e aprendizagem, já que seus gráficos são armazenados separadamente em uma página *HTML*, e que não depende nem de internete e nem de computador para sua utilização.

\

|       O `plotly` constitui portanto uma biblioteca gráfica interativa bastante significativa no *"reino"* moderno da *visualização de dados* e do *story telling*, e pode ser obtida tanto para a [linguagem `R`](https://plotly.com/r/) como para linguagem [Python](https://plotly.com/python/), e a linguagem [JavaScript](https://plotly.com/javascript/) de programação.

|       Complementarmente, por possibilitar uma integração ao *JavaScript*, a biblioteca também é utilizada em alguns paineis de dados, como no [Power Bi](https://www.microsoft.com/pt-br/power-platform/products/power-bi) da *Microsoft*, uma coleção de aplicativos conectados para a visualização de dados. De fato, é a própria biblioteca `plotlyjs`, externa ao `R` e *RStudio* que é incorporada ao `R`.


## Referência do pacote:

*   [Geral](https://cran.r-project.org/web/packages/plotly/index.html)
*   [Manual](https://cran.r-project.org/web/packages/plotly/plotly.pdf)
*   [Tutorial](https://plotly.com/r/)


